CREATE TABLE IF NOT EXISTS markets
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    item MEDIUMBLOB NOT NULL UNIQUE,
    name VARCHAR NOT NULL
);
|
CREATE TABLE IF NOT EXISTS listings
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    sellerID BINARY(128) NOT NULL,
    serverID INT NOT NULL,
    stock INT NOT NULL,
    pricePer DOUBLE NOT NULL,
    marketID INTEGER NOT NULL REFERENCES markets(id),
    CHECK (stock > 0 AND pricePer > 0)
);
|
CREATE TABLE IF NOT EXISTS payment
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    sellerID BINARY(128) NOT NULL,
    serverID INTEGER NOT NULL,
    toPay DOUBLE NOT NULL,
    CHECK (toPay > 0)
);
|
CREATE TABLE IF NOT EXISTS log
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    sellerID BINARY(128) NOT NULL,
    buyerID BINARY(128) NOT NULL,
    amountPurchased INT NOT NULL,
    amountPaid DOUBLE NOT NULL,
    marketID INTEGER NOT NULL REFERENCES markets(id),
);