name: PlayerShopOverhaul
version: ${project.version}
main: me.xemor.playershopoverhaul.PlayerShopOverhaul
api-version: 1.17
authors: [ Xemor_ ]
description: Adds the global trade system
folia-supported: true
commands:
  pso:
    usage: /pso
    description: The admin commands of PlayerShopOverhaul
    aliases: ["playershopoverhaul"]
libraries:
  - "mysql:mysql-connector-java:8.0.29"
  - "org.xerial:sqlite-jdbc:3.36.0.3"
  - "org.jdbi:jdbi3-sqlobject:3.43.0"
  - "org.jdbi:jdbi3-core:3.43.0"
  - "com.h2database:h2:2.2.224"
  - "com.fasterxml.jackson.core:jackson-core:2.18.0"
  - "com.fasterxml.jackson.core:jackson-databind:2.18.2"
  - "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.7.0"
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - packetevents
  - ProtocolLib
permissions:
  playershopoverhaul.pso.reload:
    description: Allows you to reload PlayerShopOverhaul
    default: op
  playershopoverhaul.pso.toggleplugin:
    description: Allows you to toggle the registration of /gts in PlayerShopOverhaul
    default: op
  playershopoverhaul.gts.claim:
    description: Allows you to claim your money from sellings items on the GTS
    default: true
  playershopoverhaul.gts.sell:
    description: Allows you to sell your items on the GTS
    default: true
  playershopoverhaul.gts.show:
    description: Allows you to view the items on the GTS
    default: true
  playershopoverhaul.gts.help:
    description: Shows the help message for the GTS
    default: true