CREATE TABLE IF NOT EXISTS pricedMarkets
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    item MEDIUMBLOB NOT NULL UNIQUE,
    name TEXT NOT NULL
);
|
CREATE TABLE IF NOT EXISTS listings
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    sellerID BINARY(128) NOT NULL,
    serverID INT NOT NULL,
    stock INT NOT NULL,
    pricePer DOUBLE NOT NULL,
    marketID INTEGER NOT NULL REFERENCES pricedMarkets(id),
    CHECK (stock > 0 AND pricePer > 0)
);
|
CREATE TABLE IF NOT EXISTS payment
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    sellerID BINARY(128) NOT NULL,
    serverID INTEGER NOT NULL,
    toPay DOUBLE NOT NULL,
    CHECK (toPay > 0)
);
|
CREATE TABLE IF NOT EXISTS log
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    sellerID BINARY(128) NOT NULL,
    buyerID BINARY(128) NOT NULL,
    amountPurchased INT NOT NULL,
    amountPaid DOUBLE NOT NULL,
    marketID INTEGER NOT NULL REFERENCES pricedMarkets(id)
);
|
CREATE TABLE IF NOT EXISTS nameToUUID
(
    sellerID BINARY(16) PRIMARY KEY,
    username CHAR(17)
);